FactoryDefinitions = {
  fb_news: function(props) {
    return merge({
      id: '33110852384_407906475935654',
      actions: [],
      updated_time: '2012-09-07T20:25:48+0000',
      link: 'http://www.doctorswithoutborders.org/press/release.cfm?id=6288&cat=press-release',
      type: 'link',
      description: 'Dr. Unni Karunakara, international president of MSF, will receive the award at the Library of Congress in Washington, DC, on September 8, 2012.',
      caption: 'www.doctorswithoutborders.org',
      icon: 'http://static.ak.fbcdn.net/rsrc.php/v2/yD/r/aS8ecmYRys0.gif',
      shares: { count: 154 },
      message: 'We are honored to be the first organization awarded the Fulbright Prize for International Understanding.',
      from: {
          id: '33110852384',
          name: 'Doctors Without Borders/ Médecins Sans Frontières (MSF)',
          category: 'Non-profit organization'
      },
      picture: 'http://external.ak.fbcdn.net/safe_image.php?d=AQBePU2QniGxUKFh&w=90&h=90&url=http%3A%2F%2Fwww.doctorswithoutborders.org%2Fimages%2F2012%2FMSF108057-CAR-sm.jpg',
      name: 'Doctors Without Borders to Receive 2012 J. William Fulbright Prize for International Understanding',
      created_time: '2012-09-07T20:25:48+0000',
      likes: { data: [], count: 657 },
      comments: { count: 41 },
      status_type: 'shared_story'      
    }, props);
  },
  
  tweet: function(props) {
    return merge({ created_at: 'Wed Sep 19 15:10:11 +0000 2012',
        id: 248438845538983940,
        id_str: '248438845538983937',
        text: '@brantweezy We take non-medical people, too! See the full list here: http://t.co/YQ7SaFFT',
        source: '<a href="http://www.tweetdeck.com" rel="nofollow">TweetDeck</a>',
        truncated: false,
        in_reply_to_status_id: 248263983516221440,
        in_reply_to_status_id_str: '248263983516221440',
        in_reply_to_user_id: 19697364,
        in_reply_to_user_id_str: '19697364',
        in_reply_to_screen_name: 'brantweezy',
        user: 
         { id: 14755492,
           id_str: '14755492',
           name: 'Doctors w/o Borders',
           screen_name: 'MSF_USA',
           location: 'New York, NY',
           url: 'http://www.doctorswithoutborders.org',
           description: 'Providing medical aid where it\'s needed most.',
           followers_count: 230991,
           friends_count: 578,
           listed_count: 4706,
           created_at: 'Tue May 13 06:15:39 +0000 2008',
           favourites_count: 41,
           utc_offset: -18000,
           time_zone: 'Eastern Time (US & Canada)',
           geo_enabled: false,
           verified: true,
           statuses_count: 8210,
           lang: 'en',
           contributors_enabled: true,
           is_translator: false,
           profile_background_color: '000000',
           profile_background_image_url: 'http://a0.twimg.com/profile_background_images/166317932/MSF-twitter-bkgd.jpg',
           profile_background_image_url_https: 'https://si0.twimg.com/profile_background_images/166317932/MSF-twitter-bkgd.jpg',
           profile_background_tile: false,
           profile_image_url: 'http://a0.twimg.com/profile_images/788029318/MSF-twitter-icon_normal.png',
           profile_image_url_https: 'https://si0.twimg.com/profile_images/788029318/MSF-twitter-icon_normal.png',
           profile_banner_url: 'https://si0.twimg.com/profile_banners/14755492/1348152143',
           profile_link_color: '420109',
           profile_sidebar_border_color: 'FFFFFF',
           profile_sidebar_fill_color: 'EDEDED',
           profile_text_color: '333333',
           profile_use_background_image: true,
           default_profile: false,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweet_count: 1,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false
        }, props);
  }
}
